# frozen_string_literal: true

inherit_gem:
  standard: config/base.yml

plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "tmp/**/*"
    - ".venv/**/*"
    - "coverage/**/*"

# Block length exemptions for tests and DSLs
Metrics/BlockLength:
  Exclude:
    - "test/**/*"
    - "spec/**/*"
    - "*.gemspec"
    - "Rakefile"

# Allow multiple assertions per test for comprehensive testing
Minitest/MultipleAssertions:
  Enabled: false
